/*
 Nombre: Daniel Emiliano Burrola Avalos
 Fecha: 18/11/2021
 Funcionalidad: Se pretende hacer funciones para entrenar al modelo para las futuras recomendaciones
 */

﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace GG.WebPageMVC
{
    public partial class GGMLModel
    {
       

        /// <summary>
        /// Se re entrena en PipeLine
        /// </summary>
        /// <param name="context"></param>
        /// <param name="trainData">Datos de entrenamiento</param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
          
         
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// Se construye la PipeLine que se utiliza desde el generador de modelos. 
        /// Se utiliza esta función para reentrenar el modelo. 
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Conversion.MapValueToKey(@"UserId", @"UserId")      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"TravelPackageId", @"TravelPackageId"))      
                                    .Append(mlContext.Recommendation().Trainers.MatrixFactorization(labelColumnName:@"Punctuation",matrixColumnIndexColumnName:@"UserId",matrixRowIndexColumnName:@"TravelPackageId"));

            return pipeline;
        }
    }
}
