
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace GGRecommenderSystemConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            GGMLModel.ModelInput sampleData = new GGMLModel.ModelInput()
            {
                Id = 1F,
                UserId = @"03191f72-7e34-4bbb-80e7-6da60371a156",
                TravelPackageId = 1F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = GGMLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Punctuation with predicted Punctuation from sample data...\n\n");


            Console.WriteLine($"Id: {1F}");
            Console.WriteLine($"UserId: {@"03191f72-7e34-4bbb-80e7-6da60371a156"}");
            Console.WriteLine($"TravelPackageId: {1F}");
            Console.WriteLine($"Punctuation: {1F}");


            Console.WriteLine($"\n\nPredicted Punctuation: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
